name: websend-dev
services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["/app/entrypoint.sh"]
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - .:/app
