FROM golang:1.25.4-bookworm

RUN groupadd -g 1000 dev && \
	useradd -l -u 1000 -g dev dev
RUN mkdir /home/dev
RUN chown -R dev:dev /home/dev /go

# Install Node.js
RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
	apt-get install -y nodejs build-essential

WORKDIR /app

USER dev

RUN go install github.com/bokwoon95/wgo@latest
RUN go install -tags "postgres" "github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.0"
RUN curl -sSfL "https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh" | sh -s -- -b $(go env GOPATH)/bin v2.7.2
