name: websend-backend
services:
  app:
    image: ghcr.io/lionpuro/websend-backend:latest
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    networks:
      - app
  caddy:
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:2.11.2
        RUN caddy add-package github.com/WeidiDeng/caddy-cloudflare-ip
        COPY Caddyfile /etc/caddy/Caddyfile
    restart: unless-stopped
    environment:
      - PORT=${PORT}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  app:
