name: Deploy backend

on:
  workflow_run:
    branches:
      - main
    workflows:
      - "Build backend"
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yaml"
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    if: ${{ (github.event_name != 'workflow_run') || (github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        env:
          PORT: ${{ secrets.PORT }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PORT,ALLOWED_ORIGINS
          script: |
            cd /opt/websend/infra
            git pull
            rm -f .env && touch .env
            echo PORT=$PORT >> .env
            echo ALLOWED_ORIGINS=$ALLOWED_ORIGINS >> .env
            docker compose pull && docker compose up -d --build
